title: Autonomous Vehicles Software System Tutorial
description: A comprehensive tutorial on autonomous vehicle software systems
theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

plugins:
  - jekyll-katex
  - jekyll-sitemap
  - jekyll-gist

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore 