title: Autonomous Vehicles Software System Tutorial
description: A comprehensive tutorial on autonomous vehicle software systems
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

plugins:
  - jekyll-katex
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore 